"""
TerraSentinel — Database Seeder
Seeds the database with realistic prototype data for NE India.
"""

from datetime import datetime, timedelta
from models import RiskZone, Incident, Alert, DataSource
from risk_engine import calculate_risk


def seed_database(session):
    """Seed all tables with realistic prototype data."""

    # Check if already seeded
    if session.query(RiskZone).count() > 0:
        return

    now = datetime.now()

    # ── Risk Zones ─────────────────────────────────────────
    zones = [
        RiskZone(
            id=1,
            name="Darjeeling — Zone 04",
            region="West Bengal",
            latitude=27.0360,
            longitude=88.2627,
            # Calculated by the documented prototype model from the values below.
            risk_score=39,
            risk_level="MODERATE",
            rainfall=48.0,
            soil_moisture=52.0,
            slope=34.0,
            ground_movement=False,
            historical_risk="High",
            terrain_risk="High",
            cctv_status="Online",
            prediction="Monitoring — moderate susceptibility",
            updated_at=now,
        ),
        RiskZone(
            id=2,
            name="Sikkim — NH-10 Corridor",
            region="Sikkim",
            latitude=27.3389,
            longitude=88.6065,
            risk_score=68,
            risk_level="HIGH",
            rainfall=96.0,
            soil_moisture=74.0,
            slope=42.0,
            ground_movement=True,
            historical_risk="High",
            terrain_risk="High",
            cctv_status="Online",
            prediction="Slope instability detected — elevated risk",
            updated_at=now,
        ),
        RiskZone(
            id=3,
            name="Guwahati — Zone 02",
            region="Assam",
            latitude=26.1445,
            longitude=91.7362,
            risk_score=24,
            risk_level="LOW",
            rainfall=32.0,
            soil_moisture=41.0,
            slope=12.0,
            ground_movement=False,
            historical_risk="Medium",
            terrain_risk="Low",
            cctv_status="Online",
            prediction="Normal conditions",
            updated_at=now,
        ),
        RiskZone(
            id=4,
            name="Itanagar — Zone 01",
            region="Arunachal Pradesh",
            latitude=27.0844,
            longitude=93.6053,
            risk_score=56,
            risk_level="HIGH",
            rainfall=88.0,
            soil_moisture=68.0,
            slope=38.0,
            ground_movement=False,
            historical_risk="High",
            terrain_risk="High",
            cctv_status="Online",
            prediction="Heavy rainfall — monitor closely",
            updated_at=now,
        ),
        RiskZone(
            id=5,
            name="Shillong — Zone 08",
            region="Meghalaya",
            latitude=25.5788,
            longitude=91.8933,
            risk_score=61,
            risk_level="HIGH",
            rainfall=104.0,
            soil_moisture=72.0,
            slope=28.0,
            ground_movement=False,
            historical_risk="High",
            terrain_risk="Medium",
            cctv_status="Online",
            prediction="Heavy rainfall threshold exceeded",
            updated_at=now,
        ),
        RiskZone(
            id=6,
            name="Kohima — Zone 03",
            region="Nagaland",
            latitude=25.6751,
            longitude=94.1086,
            risk_score=42,
            risk_level="MODERATE",
            rainfall=56.0,
            soil_moisture=58.0,
            slope=32.0,
            ground_movement=False,
            historical_risk="Medium",
            terrain_risk="Medium",
            cctv_status="Online",
            prediction="Moderate rainfall — standard monitoring",
            updated_at=now,
        ),
        RiskZone(
            id=7,
            name="Imphal — Zone 05",
            region="Manipur",
            latitude=24.8170,
            longitude=93.9368,
            risk_score=18,
            risk_level="LOW",
            rainfall=22.0,
            soil_moisture=36.0,
            slope=14.0,
            ground_movement=False,
            historical_risk="Low",
            terrain_risk="Low",
            cctv_status="Online",
            prediction="Normal conditions",
            updated_at=now,
        ),
        RiskZone(
            id=8,
            name="Aizawl — Zone 06",
            region="Mizoram",
            latitude=23.7271,
            longitude=92.7176,
            risk_score=47,
            risk_level="MODERATE",
            rainfall=68.0,
            soil_moisture=62.0,
            slope=36.0,
            ground_movement=False,
            historical_risk="Medium",
            terrain_risk="High",
            cctv_status="Offline",
            prediction="Moderate risk — terrain susceptibility noted",
            updated_at=now,
        ),
        RiskZone(
            id=9,
            name="Agartala — Zone 07",
            region="Tripura",
            latitude=23.8315,
            longitude=91.2868,
            risk_score=15,
            risk_level="LOW",
            rainfall=18.0,
            soil_moisture=32.0,
            slope=8.0,
            ground_movement=False,
            historical_risk="Low",
            terrain_risk="Low",
            cctv_status="Online",
            prediction="Normal conditions",
            updated_at=now,
        ),
    ]
    session.add_all(zones)

    # ── Incidents ──────────────────────────────────────────
    incidents = [
        Incident(
            id=1,
            incident_code="TS-001",
            location="Sikkim — NH-10 Corridor",
            type="Slope Instability",
            risk_score=68,
            severity="HIGH",
            status="Monitoring",
            detected_at="13:18",
            description="Slope instability detected along NH-10 corridor near Rangpo.",
            cause="Heavy rainfall + weak geological formation",
            zone_id=2,
        ),
        Incident(
            id=2,
            incident_code="TS-002",
            location="Shillong — Zone 08",
            type="Heavy Rainfall",
            risk_score=61,
            severity="HIGH",
            status="Active",
            detected_at="11:45",
            description="Heavy rainfall threshold exceeded in Meghalaya Zone 08.",
            cause="Sustained heavy rainfall exceeding 100mm/24h",
            zone_id=5,
        ),
        Incident(
            id=3,
            incident_code="TS-003",
            location="Itanagar — Zone 01",
            type="Landslide Warning",
            risk_score=56,
            severity="HIGH",
            status="Active",
            detected_at="09:22",
            description="Elevated landslide probability in Itanagar sector.",
            cause="Heavy rainfall + steep terrain",
            zone_id=4,
        ),
    ]
    session.add_all(incidents)

    # ── Alerts ─────────────────────────────────────────────
    alerts = [
        Alert(
            id=1,
            severity="HIGH",
            location="Sikkim — NH-10 Corridor",
            message="Slope instability detected along NH-10 corridor. Ground movement sensors triggered.",
            recommendation="Increase monitoring frequency. Prepare field response team for deployment.",
            status="Active",
            zone_id=2,
            created_at=now - timedelta(hours=2),
        ),
        Alert(
            id=2,
            severity="HIGH",
            location="Shillong — Zone 08",
            message="Heavy rainfall threshold exceeded. 104mm recorded in last 24 hours.",
            recommendation="Continue monitoring. Review rainfall trend. Notify authorities if trend continues.",
            status="Active",
            zone_id=5,
            created_at=now - timedelta(hours=4),
        ),
        Alert(
            id=3,
            severity="MODERATE",
            location="Itanagar — Zone 01",
            message="Elevated rainfall and soil moisture levels. Monitor for potential slope instability.",
            recommendation="Continue standard monitoring. Review rainfall trend for next 12 hours.",
            status="Active",
            zone_id=4,
            created_at=now - timedelta(hours=6),
        ),
    ]
    session.add_all(alerts)

    # ── Data Sources ───────────────────────────────────────
    data_sources = [
        DataSource(
            id=1,
            name="ARGUS Visual Intelligence",
            type="CCTV / Visual AI",
            source="CCTV / RTSP feeds",
            status="Connected",
            mode="Simulated",
            active_count=8,
            last_updated=now - timedelta(minutes=2),
            metadata_info='{"module": "EXTERNAL AI MODULE", "confidence": 0.94, "detection": "Ground movement detected", "note": "ARGUS is an independent AI/CCTV visual intelligence module feeding TerraSentinel."}',
        ),
        DataSource(
            id=2,
            name="IMD Weather Data",
            type="Meteorological",
            source="India Meteorological Department",
            status="Connected",
            mode="Simulated",
            active_count=12,
            last_updated=now - timedelta(minutes=5),
            metadata_info='{"data_types": ["rainfall", "temperature", "humidity", "wind_speed"], "update_interval": "15min"}',
        ),
        DataSource(
            id=3,
            name="Soil Moisture Sensors",
            type="IoT Sensors",
            source="In-situ soil sensors",
            status="Connected",
            mode="Simulated",
            active_count=42,
            last_updated=now - timedelta(minutes=1),
            metadata_info='{"sensor_types": ["capacitive", "TDR"], "depth_range": "0.3m - 2m"}',
        ),
        DataSource(
            id=4,
            name="Satellite Remote Sensing",
            type="Satellite Imagery",
            source="ISRO / Sentinel-2",
            status="Available",
            mode="Simulated",
            active_count=0,
            last_updated=now - timedelta(hours=3),
            metadata_info='{"resolution": "10m", "revisit": "5 days", "bands": ["optical", "SAR"]}',
        ),
        DataSource(
            id=5,
            name="GIS / DEM Data",
            type="Terrain Analysis",
            source="SRTM / CartoDEM",
            status="Connected",
            mode="Static",
            active_count=0,
            last_updated=now - timedelta(days=1),
            metadata_info='{"resolution": "30m", "coverage": "North-East India", "data": ["elevation", "slope", "aspect"]}',
        ),
        DataSource(
            id=6,
            name="Citizen Reports",
            type="Crowdsourced",
            source="Mobile App / Web Portal",
            status="Active",
            mode="Simulated",
            active_count=156,
            last_updated=now - timedelta(minutes=15),
            metadata_info='{"report_types": ["geo-tagged photos", "text reports", "damage assessment"], "verified": 89}',
        ),
    ]
    session.add_all(data_sources)

    session.commit()
